export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CREATE_BOOKING_BEGIN = "CREATE_BOOKING_BEGIN";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";

export const GET_BOOKINGS_BEGIN = "GET_BOOKINGS_BEGIN";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";

export const GET_BOOKING_BEGIN = "GET_BOOKING_BEGIN";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";

export const DELETE_BOOKING_BEGIN = "DELETE_BOOKING_BEGIN";

export const UPDATE_BOOKING_BEGIN = "UPDATE_BOOKING_BEGIN";
